### PR TITLE
Windows EXE icon - issue #5

### PR DESCRIPTION
**Pull request by dparnell**
I've extracted the icon from the MacOS resource and added in stuff to the build script to set the icon for the executable. I was hoping this would set the icon for the window as well, but it only seems to set the icon for the shell window that opens. It's a start.

### CODE REVIEW

**Comment by zacps** [comment]
This errors for me with `assets/windows.rc(1) : fatal error RC1015: cannot open include file 'winuser.h'.`.
Running `RC.exe` manually with the `/i` (include) switch pointing to an SDK header directory (`C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um` in my case) works.

Did you have to do anything extra to get it to work? It's possible it's the result of a broken install on my end. `RC.exe` also mentions an `INCLUDE` environment variable, do you have that set to anything?

**Comment by dparnell** [comment]
I'm running it using the "x64 Native Tools Command Prompt for VS 2017" and I didn't do anything extra to get it to work. I imagine that the shortcut sets some environment variables and pathing so that `RC.exe` can find things correctly. I wonder if the include is even needed...

**Comment by dparnell** [comment]
It seems to work without the include :)

**Comment by zacps** [comment]
That fixes the build. Combined with adding a [windows subsystem attribute](https://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window/29764309#29764309) it also produces the correct icon in the taskbar. However as you say it doesn't display in the corner of the window.

It looks it might be [winit#69](https://github.com/tomaka/winit/issues/69) that we need fixed. Merging for now and I'll revisit #5 later on.

**Pull request merged**
